alx

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -9,6 +9,13 @@
 if [ $# -lt 4 ]
 then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
+fi
+  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
+
+if [ $? -eq 0]
+then 
+	echo "file was transferred succesfully"
 else
-  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
+	echo "file tranfer failed"
 fi
